travis:
  secure:
    BINSTAR_TOKEN: GGcOueFBFPigGVOEFRXg0dOb1HhoGOtzlVppgxO6hDaEhYkc7uM9f6sW1gBmrgH1c2UCei0uSgHyHx4wLf3jmyjR2J47yOmwTZLd49QUGz6N3dhdv9tNjJtdW3PStcthJ2X8fIUxifXq4TvDQEhV0kZTf66ApSN4QErJR8VcbQ/GrTAMSXmNU9p1etpcnJlJk3LovwP4YnbNQ8X+PVyjnLEISfNNOxaqJJvlweYeooS7wIGdoqlm1Jw5TLpCt9qOsw6IYh3RHyby/lzsZQ+ZYWSrTcWf18uJ4JGMvHXNYtlLfe8mFegjbZHQzX4ed9+kv/SR+JWE0tyeIhSdl6ydnGPiyGY68SWi8JMTaavvbyz/o2u2MBaVeI1deEF0yWVRkL7CB6Ap5zfP+PhYs2/RdDI4kdTFZkLsro//SOe/Il05TTTLxkTVO3ggguwZWpF+CcuA34KjqKpG/BRDI9kfRaEmTMAd36pRMomVnE2zNMUJC4m4Q2g8SxfqUHyqQNrlPmpSTtpe8vIpvKqOCIcUUDmmG4M69Osd6x1QvuSOkr0YForZ6jPVAtPb8aDeZyL6CZlQQiLz/jcQli72wqHYhxVI8cqiMZ3z9dEpo7CursNp0Fkbuabk+aClE/xzTOJ8BuPY2WgVF+7AxH2prSSo1zDZKKHtJZOeGoHcDvVG6iY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
